/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestion_reservation (void)
{
  GtkWidget *gestion_reservation;
  GtkWidget *notebook2;
  GtkWidget *fixed3;
  GtkWidget *nom;
  GtkWidget *prenom;
  GtkWidget *cin;
  GtkWidget *telephone;
  GtkWidget *label24;
  GtkWidget *label23;
  GtkWidget *label26;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label69;
  GtkWidget *label68;
  GtkWidget *label70;
  GtkWidget *label27;
  GtkWidget *label51;
  GtkWidget *label71;
  GtkWidget *button_ajouter;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *label60;
  GtkWidget *label25;
  GtkWidget *combobox1;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkWidget *label20;
  GtkWidget *label15;
  GtkWidget *fixed4;
  GtkWidget *nom2;
  GtkWidget *prenom1;
  GtkWidget *cin1;
  GtkWidget *telephone1;
  GtkWidget *togglebutton8;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label56;
  GtkWidget *entry_id;
  GtkObject *sjour1_adj;
  GtkWidget *sjour1;
  GtkObject *sannee1_adj;
  GtkWidget *sannee1;
  GtkWidget *buttonverif;
  GtkWidget *button_modifier;
  GtkWidget *parking1;
  GtkWidget *label180;
  GtkWidget *label250;
  GtkWidget *label210;
  GtkWidget *label230;
  GtkWidget *label240;
  GtkWidget *label270;
  GtkWidget *label260;
  GtkWidget *label200;
  GtkWidget *label190;
  GtkWidget *label220;
  GtkObject *smois1_adj;
  GtkWidget *smois1;
  GtkWidget *label16;
  GtkWidget *fixed5;
  GtkWidget *id1;
  GtkWidget *togglebutton9;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label57;
  GtkWidget *label31;
  GtkWidget *msg1;
  GtkWidget *label32;
  GtkWidget *label72;
  GtkWidget *label33;
  GtkWidget *button_supprimer;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *label62;
  GtkWidget *label17;
  GtkWidget *fixed11;
  GtkWidget *togglebutton10;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label58;
  GtkWidget *label35;
  GtkWidget *button21;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label61;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *fixed12;
  GtkWidget *treeview1;
  GtkWidget *label18;
  GtkWidget *fixed13;
  GtkWidget *button28;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image42;
  GtkWidget *label64;
  GtkWidget *label65;
  GtkWidget *label67;
  GtkWidget *scrolledwindow3;
  GtkWidget *viewport3;
  GtkWidget *fixed16;
  GtkWidget *treeview2;
  GtkWidget *comboboxentry1;
  GtkWidget *label19;

  gestion_reservation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_reservation), _("window2"));

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_container_add (GTK_CONTAINER (gestion_reservation), notebook2);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed3);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed3), nom, 208, 104);
  gtk_widget_set_size_request (nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  prenom = gtk_entry_new ();
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed3), prenom, 210, 160);
  gtk_widget_set_size_request (prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom), 8226);

  cin = gtk_entry_new ();
  gtk_widget_show (cin);
  gtk_fixed_put (GTK_FIXED (fixed3), cin, 208, 216);
  gtk_widget_set_size_request (cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cin), 8226);

  telephone = gtk_entry_new ();
  gtk_widget_show (telephone);
  gtk_fixed_put (GTK_FIXED (fixed3), telephone, 208, 336);
  gtk_widget_set_size_request (telephone, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (telephone), 8226);

  label24 = gtk_label_new (_("nom parking : "));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 80, 280);
  gtk_widget_set_size_request (label24, 100, 17);

  label23 = gtk_label_new (_("id de reservation "));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 48, 432);
  gtk_widget_set_size_request (label23, 220, 17);

  label26 = gtk_label_new (_("telephone"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed3), label26, 40, 344);
  gtk_widget_set_size_request (label26, 150, 17);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 0);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed3), jour, 912, 64);
  gtk_widget_set_size_request (jour, 72, 32);

  annee_adj = gtk_adjustment_new (1922, 2024, 2025, 1, 10, 0);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed3), annee, 904, 184);
  gtk_widget_set_size_request (annee, 72, 32);

  label21 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 80, 160);
  gtk_widget_set_size_request (label21, 75, 17);

  label22 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 88, 224);
  gtk_widget_set_size_request (label22, 41, 16);

  label69 = gtk_label_new (_("mois "));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed3), label69, 784, 128);
  gtk_widget_set_size_request (label69, 56, 24);

  label68 = gtk_label_new (_("jour"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed3), label68, 840, 72);
  gtk_widget_set_size_request (label68, 56, 24);

  label70 = gtk_label_new (_("annee "));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed3), label70, 840, 184);
  gtk_widget_set_size_request (label70, 56, 32);

  label27 = gtk_label_new (_("votre r\303\251servation a \303\251t\303\251 ajout\303\251 avec succ\303\251s \nmerci pour votre confiance \360\237\214\237\360\237\230\212"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed3), label27, 632, 520);
  gtk_widget_set_size_request (label27, 296, 72);

  label51 = gtk_label_new ("");
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed3), label51, 264, 424);
  gtk_widget_set_size_request (label51, 128, 40);

  label71 = gtk_label_new ("");
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed3), label71, 704, 432);
  gtk_widget_set_size_request (label71, 168, 88);

  button_ajouter = gtk_button_new ();
  gtk_widget_show (button_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed3), button_ajouter, 728, 592);
  gtk_widget_set_size_request (button_ajouter, 90, 31);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_ajouter), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  label60 = gtk_label_new_with_mnemonic (_("Ajouter "));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox6), label60, FALSE, FALSE, 0);

  label25 = gtk_label_new (_("date de r\303\251servation :"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed3), label25, 624, 80);
  gtk_widget_set_size_request (label25, 150, 17);
  gtk_misc_set_padding (GTK_MISC (label25), 0, 2);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox1, 216, 272);
  gtk_widget_set_size_request (combobox1, 152, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("parkinA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("parkingB"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("parkinC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("parkingD"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("parkinC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("parkingF"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), "");

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 0);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed3), mois, 920, 128);
  gtk_widget_set_size_request (mois, 60, 27);

  label20 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 88, 104);
  gtk_widget_set_size_request (label20, 50, 20);

  label15 = gtk_label_new (_("Ajouter une r\303\251servation \360\237\223\245"));
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label15);
  gtk_widget_set_size_request (label15, 190, -1);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed4);

  nom2 = gtk_entry_new ();
  gtk_widget_show (nom2);
  gtk_fixed_put (GTK_FIXED (fixed4), nom2, 208, 96);
  gtk_widget_set_size_request (nom2, 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom2), 8226);

  prenom1 = gtk_entry_new ();
  gtk_widget_show (prenom1);
  gtk_fixed_put (GTK_FIXED (fixed4), prenom1, 208, 152);
  gtk_widget_set_size_request (prenom1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom1), 8226);

  cin1 = gtk_entry_new ();
  gtk_widget_show (cin1);
  gtk_fixed_put (GTK_FIXED (fixed4), cin1, 208, 216);
  gtk_widget_set_size_request (cin1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cin1), 8226);

  telephone1 = gtk_entry_new ();
  gtk_widget_show (telephone1);
  gtk_fixed_put (GTK_FIXED (fixed4), telephone1, 208, 368);
  gtk_widget_set_size_request (telephone1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (telephone1), 8226);

  togglebutton8 = gtk_toggle_button_new ();
  gtk_widget_show (togglebutton8);
  gtk_fixed_put (GTK_FIXED (fixed4), togglebutton8, 0, 0);
  gtk_widget_set_size_request (togglebutton8, 109, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (togglebutton8), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("Retour "));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox2), label56, FALSE, FALSE, 0);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_id, 208, 48);
  gtk_widget_set_size_request (entry_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  sjour1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 0);
  sjour1 = gtk_spin_button_new (GTK_ADJUSTMENT (sjour1_adj), 1, 0);
  gtk_widget_show (sjour1);
  gtk_fixed_put (GTK_FIXED (fixed4), sjour1, 760, 128);
  gtk_widget_set_size_request (sjour1, 60, 27);

  sannee1_adj = gtk_adjustment_new (1, 2024, 2027, 1, 10, 0);
  sannee1 = gtk_spin_button_new (GTK_ADJUSTMENT (sannee1_adj), 1, 0);
  gtk_widget_show (sannee1);
  gtk_fixed_put (GTK_FIXED (fixed4), sannee1, 952, 128);
  gtk_widget_set_size_request (sannee1, 60, 27);

  buttonverif = gtk_button_new_with_mnemonic (_("verifier "));
  gtk_widget_show (buttonverif);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonverif, 416, 40);
  gtk_widget_set_size_request (buttonverif, 74, 29);

  button_modifier = gtk_button_new_with_mnemonic (_("Modifier \342\234\217\357\270\217 "));
  gtk_widget_show (button_modifier);
  gtk_fixed_put (GTK_FIXED (fixed4), button_modifier, 680, 528);
  gtk_widget_set_size_request (button_modifier, 100, 31);

  parking1 = gtk_combo_box_new_text ();
  gtk_widget_show (parking1);
  gtk_fixed_put (GTK_FIXED (fixed4), parking1, 208, 280);
  gtk_widget_set_size_request (parking1, 152, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (parking1), _("parkinA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (parking1), _("parkingB"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (parking1), _("parkinC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (parking1), _("parkingD"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (parking1), _("parkinC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (parking1), _("parkingF"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (parking1), "");

  label180 = gtk_label_new (_("id"));
  gtk_widget_show (label180);
  gtk_fixed_put (GTK_FIXED (fixed4), label180, 120, 56);
  gtk_widget_set_size_request (label180, 49, 17);

  label250 = gtk_label_new (_("votre r\303\251servation a \303\251t\303\251 modifi\303\251 avec succ\303\251s \nmerci pour votre confiance \360\237\214\237\360\237\230\212"));
  gtk_widget_show (label250);
  gtk_fixed_put (GTK_FIXED (fixed4), label250, 584, 576);
  gtk_widget_set_size_request (label250, 300, 40);

  label210 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label210);
  gtk_fixed_put (GTK_FIXED (fixed4), label210, 120, 224);
  gtk_widget_set_size_request (label210, 49, 17);

  label230 = gtk_label_new (_("t\303\251l\303\251phone : "));
  gtk_widget_show (label230);
  gtk_fixed_put (GTK_FIXED (fixed4), label230, 88, 376);
  gtk_widget_set_size_request (label230, 90, 17);

  label240 = gtk_label_new (_("date de r\303\251servation :"));
  gtk_widget_show (label240);
  gtk_fixed_put (GTK_FIXED (fixed4), label240, 592, 136);
  gtk_widget_set_size_request (label240, 150, 17);

  label270 = gtk_label_new ("");
  gtk_widget_show (label270);
  gtk_fixed_put (GTK_FIXED (fixed4), label270, 504, 24);
  gtk_widget_set_size_request (label270, 184, 48);

  label260 = gtk_label_new ("");
  gtk_widget_show (label260);
  gtk_fixed_put (GTK_FIXED (fixed4), label260, 624, 496);
  gtk_widget_set_size_request (label260, 224, 32);

  label200 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label200);
  gtk_fixed_put (GTK_FIXED (fixed4), label200, 112, 160);
  gtk_widget_set_size_request (label200, 75, 17);

  label190 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label190);
  gtk_fixed_put (GTK_FIXED (fixed4), label190, 128, 104);
  gtk_widget_set_size_request (label190, 50, 20);

  label220 = gtk_label_new (_("nom parking : "));
  gtk_widget_show (label220);
  gtk_fixed_put (GTK_FIXED (fixed4), label220, 88, 288);
  gtk_widget_set_size_request (label220, 100, 17);

  smois1_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 0);
  smois1 = gtk_spin_button_new (GTK_ADJUSTMENT (smois1_adj), 1, 0);
  gtk_widget_show (smois1);
  gtk_fixed_put (GTK_FIXED (fixed4), smois1, 864, 128);
  gtk_widget_set_size_request (smois1, 60, 27);

  label16 = gtk_label_new (_("Modifier une r\303\251servation \342\234\217\357\270\217 "));
  gtk_widget_show (label16);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label16);
  gtk_widget_set_size_request (label16, 190, -1);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed5);

  id1 = gtk_entry_new ();
  gtk_widget_show (id1);
  gtk_fixed_put (GTK_FIXED (fixed5), id1, 528, 304);
  gtk_widget_set_size_request (id1, 296, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (id1), 8226);

  togglebutton9 = gtk_toggle_button_new ();
  gtk_widget_show (togglebutton9);
  gtk_fixed_put (GTK_FIXED (fixed5), togglebutton9, 0, 0);
  gtk_widget_set_size_request (togglebutton9, 112, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (togglebutton9), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Retour "));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox3), label57, FALSE, FALSE, 0);

  label31 = gtk_label_new (_("donner l'identifiant de la r\303\251servation\nque souhaitez vous supprimer \360\237\206\224"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 296, 216);
  gtk_widget_set_size_request (label31, 260, 36);

  msg1 = gtk_label_new ("");
  gtk_widget_show (msg1);
  gtk_fixed_put (GTK_FIXED (fixed5), msg1, 1000, 104);
  gtk_widget_set_size_request (msg1, 216, 184);

  label32 = gtk_label_new (_("\303\212tes-vous s\303\273r de vouloir supprimer cette r\303\251servation ? "));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed5), label32, 528, 408);
  gtk_widget_set_size_request (label32, 370, 17);

  label72 = gtk_label_new ("");
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed5), label72, 632, 480);
  gtk_widget_set_size_request (label72, 192, 80);

  label33 = gtk_label_new (_("NB \360\237\223\214 : toute personne qui effectue une r\303\251servation et ne se pr\303\251sente\n pas sera sanctionn\303\251e par une interdiction de r\303\251servation d'un mois . "));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed5), label33, 472, 432);
  gtk_widget_set_size_request (label33, 480, 35);

  button_supprimer = gtk_button_new ();
  gtk_widget_show (button_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed5), button_supprimer, 672, 560);
  gtk_widget_set_size_request (button_supprimer, 110, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_supprimer), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  label62 = gtk_label_new_with_mnemonic (_("Supprimer "));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox8), label62, FALSE, FALSE, 0);

  label17 = gtk_label_new (_("Supprimer une r\303\251servation \360\237\227\221\357\270\217"));
  gtk_widget_show (label17);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label17);
  gtk_widget_set_size_request (label17, 200, -1);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed11);

  togglebutton10 = gtk_toggle_button_new ();
  gtk_widget_show (togglebutton10);
  gtk_fixed_put (GTK_FIXED (fixed11), togglebutton10, 0, 0);
  gtk_widget_set_size_request (togglebutton10, 109, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (togglebutton10), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("Retour "));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox4), label58, FALSE, FALSE, 0);

  label35 = gtk_label_new (_("voici la liste des r\303\251servations . si vous avez une r\303\251clamation \nn'hesitez pas a contacter notre service client \342\255\220\357\270\217"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed11), label35, 56, 72);
  gtk_widget_set_size_request (label35, 450, 35);

  button21 = gtk_button_new ();
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed11), button21, 992, 600);
  gtk_widget_set_size_request (button21, 230, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button21), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("merci pour votre vesite \360\237\214\237\360\237\230\212"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox7), label61, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed11), scrolledwindow1, 376, 128);
  gtk_widget_set_size_request (scrolledwindow1, 600, 400);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed12);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed12), treeview1, 0, 0);
  gtk_widget_set_size_request (treeview1, 600, 392);

  label18 = gtk_label_new (_("Afficher les r\303\251servations \360\237\221\200  "));
  gtk_widget_show (label18);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), label18);
  gtk_widget_set_size_request (label18, 220, 22);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed13);

  button28 = gtk_button_new ();
  gtk_widget_show (button28);
  gtk_fixed_put (GTK_FIXED (fixed13), button28, 0, 0);
  gtk_widget_set_size_request (button28, 104, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button28), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image42 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image42);
  gtk_box_pack_start (GTK_BOX (hbox10), image42, FALSE, FALSE, 0);

  label64 = gtk_label_new_with_mnemonic (_("retour "));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox10), label64, FALSE, FALSE, 0);

  label65 = gtk_label_new (_("choisissez un parking "));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed13), label65, 520, 544);
  gtk_widget_set_size_request (label65, 180, 22);

  label67 = gtk_label_new (_("v oici la liste des parkings tri\303\251 "));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed13), label67, 216, 64);
  gtk_widget_set_size_request (label67, 240, 24);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed13), scrolledwindow3, 320, 104);
  gtk_widget_set_size_request (scrolledwindow3, 600, 400);

  viewport3 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), viewport3);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (viewport3), fixed16);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed16), treeview2, 0, 0);
  gtk_widget_set_size_request (treeview2, 600, 392);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed13), comboboxentry1, 704, 536);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Parking A "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Parking B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Parking C "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Parking D "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Parking E "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Parking F "));

  label19 = gtk_label_new (_("R\303\251servations tri\303\251s \360\237\227\223\357\270\217"));
  gtk_widget_show (label19);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 4), label19);
  gtk_widget_set_size_request (label19, 200, -1);

  g_signal_connect ((gpointer) button_ajouter, "clicked",
                    G_CALLBACK (on_button_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonverif, "clicked",
                    G_CALLBACK (on_buttonverif_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier, "clicked",
                    G_CALLBACK (on_button_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer, "clicked",
                    G_CALLBACK (on_button_supprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_reservation, gestion_reservation, "gestion_reservation");
  GLADE_HOOKUP_OBJECT (gestion_reservation, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (gestion_reservation, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (gestion_reservation, nom, "nom");
  GLADE_HOOKUP_OBJECT (gestion_reservation, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (gestion_reservation, cin, "cin");
  GLADE_HOOKUP_OBJECT (gestion_reservation, telephone, "telephone");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label24, "label24");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label23, "label23");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label26, "label26");
  GLADE_HOOKUP_OBJECT (gestion_reservation, jour, "jour");
  GLADE_HOOKUP_OBJECT (gestion_reservation, annee, "annee");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label21, "label21");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label22, "label22");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label69, "label69");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label68, "label68");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label70, "label70");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label27, "label27");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label51, "label51");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label71, "label71");
  GLADE_HOOKUP_OBJECT (gestion_reservation, button_ajouter, "button_ajouter");
  GLADE_HOOKUP_OBJECT (gestion_reservation, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_reservation, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label60, "label60");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label25, "label25");
  GLADE_HOOKUP_OBJECT (gestion_reservation, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, mois, "mois");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label20, "label20");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label15, "label15");
  GLADE_HOOKUP_OBJECT (gestion_reservation, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gestion_reservation, nom2, "nom2");
  GLADE_HOOKUP_OBJECT (gestion_reservation, prenom1, "prenom1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, cin1, "cin1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, telephone1, "telephone1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, togglebutton8, "togglebutton8");
  GLADE_HOOKUP_OBJECT (gestion_reservation, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (gestion_reservation, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gestion_reservation, image2, "image2");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label56, "label56");
  GLADE_HOOKUP_OBJECT (gestion_reservation, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (gestion_reservation, sjour1, "sjour1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, sannee1, "sannee1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, buttonverif, "buttonverif");
  GLADE_HOOKUP_OBJECT (gestion_reservation, button_modifier, "button_modifier");
  GLADE_HOOKUP_OBJECT (gestion_reservation, parking1, "parking1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label180, "label180");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label250, "label250");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label210, "label210");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label230, "label230");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label240, "label240");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label270, "label270");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label260, "label260");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label200, "label200");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label190, "label190");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label220, "label220");
  GLADE_HOOKUP_OBJECT (gestion_reservation, smois1, "smois1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label16, "label16");
  GLADE_HOOKUP_OBJECT (gestion_reservation, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (gestion_reservation, id1, "id1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, togglebutton9, "togglebutton9");
  GLADE_HOOKUP_OBJECT (gestion_reservation, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion_reservation, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion_reservation, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label57, "label57");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label31, "label31");
  GLADE_HOOKUP_OBJECT (gestion_reservation, msg1, "msg1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label32, "label32");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label72, "label72");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label33, "label33");
  GLADE_HOOKUP_OBJECT (gestion_reservation, button_supprimer, "button_supprimer");
  GLADE_HOOKUP_OBJECT (gestion_reservation, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (gestion_reservation, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label62, "label62");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion_reservation, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (gestion_reservation, togglebutton10, "togglebutton10");
  GLADE_HOOKUP_OBJECT (gestion_reservation, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_reservation, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_reservation, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label58, "label58");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label35, "label35");
  GLADE_HOOKUP_OBJECT (gestion_reservation, button21, "button21");
  GLADE_HOOKUP_OBJECT (gestion_reservation, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gestion_reservation, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (gestion_reservation, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label61, "label61");
  GLADE_HOOKUP_OBJECT (gestion_reservation, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (gestion_reservation, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label18, "label18");
  GLADE_HOOKUP_OBJECT (gestion_reservation, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (gestion_reservation, button28, "button28");
  GLADE_HOOKUP_OBJECT (gestion_reservation, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (gestion_reservation, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (gestion_reservation, image42, "image42");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label64, "label64");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label65, "label65");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label67, "label67");
  GLADE_HOOKUP_OBJECT (gestion_reservation, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (gestion_reservation, viewport3, "viewport3");
  GLADE_HOOKUP_OBJECT (gestion_reservation, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (gestion_reservation, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (gestion_reservation, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (gestion_reservation, label19, "label19");

  return gestion_reservation;
}

